### ISSUE TITLE
Missing menu text on real android phones

### ISSUE THREAD

**Issue by mikan66** [brminnick/HelloMauiToolkit#25]
Going with XAML only.

**Comment by brminnick** [comment]
I'm a bit confused. The sample app in this repo is a one-page app that doesn't have a fly-out menu.

**Comment by mikan66** [comment]
I'm sorry, I should have placed this question under your project https://github.com/brminnick/HelloMauiMarkup.
I now see that the emulator doesn't show the menu like in the above pic taken from an actual android phone.  I was trying to learn and experiment with Markup doing something like this:

![image](https://github.com/brminnick/HelloMauiToolkit/assets/4913543/04a3ebcb-d49e-4536-b3ad-8983da9b6b9a)

This works on Windows Machine, but looks like the above picture on an actual Android device.  The menu text doesn't show up, all you get is a blank menu. Is there a way to control this from Markup, or do I need to switch to XAML?   Again, sorry for the confusion, my fault.
